plink: "/arc/project/st-dennisjk-1/software/plink1.9/plink"
plink2: "/arc/project/st-dennisjk-1/software/plink2.0/plink2"
flashpca: "/arc/project/st-dennisjk-1/software/flashpca/flashpca_x86-64"
bcftools: "/arc/project/st-dennisjk-1/software/bcftools-1.10.2/bcftools"
tabix: "/arc/project/st-dennisjk-1/software/htslib-1.10.2/tabix"
kg_data: "/arc/project/st-dennisjk-1/shared/data/1000G_phase3_plink/all_phase3_biallelic_autosome"
kg_data_pre_pca: "/arc/project/st-dennisjk-1/shared/data/1000G_phase3_plink/all_phase3_biallelic_autosome_pre_pca"
kg_panel: "/arc/project/st-dennisjk-1/shared/data/1000G_phase3_info/integrated_call_samples_v3.20130502.ALL.panel"
kg_vars: "/arc/project/st-dennisjk-1/shared/data/1000G_phase3_info/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz"
LD: "/arc/project/st-dennisjk-1/wcasazza/genotype_QC_resources/longrange_ld.txt"
mhc: "/arc/project/st-dennisjk-1/wcasazza/genotype_QC_resources/mhc_region.txt"
hg19: "/arc/project/st-dennisjk-1/shared/data/1000G_phase3_info/human_g1k_v37.fasta"
threads: "20"
Rscript: "/usr/local/bin/Rscript"
